version: "3"
services:
  app:
    build:
      context: ./docker/php
      args:
        - TZ=${TZ:-Europe/Istanbul}
    ports:
      - ${APP_PORT:-8000}:8000
    links: 
      - db
    volumes:
      - ${PROJECT_PATH:-./src}:/work
      - ./docker/ash:/etc/profile.d
      - ./docker/php/psysh:/root/.config/psysh
      - ./logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /work
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=${DB_NAME:-laravel}
      - DB_USERNAME=${DB_USER:-laravel}
      - DB_PASSWORD=${DB_PASS:-123.456}
      - TZ=${TZ:-Europe/Istanbul}
      - MAIL_HOST=${MAIL_HOST:-mail}
      - MAIL_PORT=${MAIL_PORT:-1025}
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_DRIVER=redis
      - REDIS_HOST=redis

  web:
    image: nginx:1.17-alpine
    depends_on:
      - app
    links: 
      - db
    ports:
      - ${WEB_PORT:-8080}:80
    volumes:
      - ${PROJECT_PATH:-./src}:/work
      - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ:-Europe/Istanbul}

  db:
    image: mysql:8.0
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME:-laravel}
      - MYSQL_USER=${DB_USER:-laravel}
      - MYSQL_PASSWORD=${DB_PASS:-123.456}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-123.456}
      - TZ=${TZ:-Europe/Istanbul}
    ports:
      - ${DB_PORT:-3306}:3306

  db-testing:
    image: mysql:8.0
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    tmpfs:
      - /var/lib/mysql
      - /var/log/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME:-laravel}
      - MYSQL_USER=${DB_USER:-laravel}
      - MYSQL_PASSWORD=${DB_PASS:-123.456}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-123.456}
      - TZ=${TZ:-Europe/Istanbul}
    ports:
      - ${DB_TESTING_PORT:-3307}:3306

  node:
    image: node:12.14-alpine
    tty: true
    volumes:
      - ${PROJECT_PATH:-./src}:/work
    working_dir: /work

  redis:
    image: redis:5.0-alpine
    volumes:
      - redis-store:/data

  mail:
    image: mailhog/mailhog
    ports:
      - ${MAILHOG_PORT:-8025}:8025

volumes:
  db-store:
  redis-store:
